# Generated by Django 6.0.3 on 2026-03-31 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_mailing_campaign",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_attempts",
                to="mailing.campaign",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailing.message", verbose_name="Сообщение"
            ),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_subscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="recipients",
            field=models.ManyToManyField(to="mailing.subscriber", verbose_name="Получатели"),
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(fields=["email"], name="mailing_sub_email_79d77f_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(fields=["is_active"], name="mailing_sub_is_acti_4a7aac_idx"),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["start_time"], name="mailing_cam_start_t_98977d_idx"),
        ),
    ]
