# Generated by Django 6.0.3 on 2026-04-05 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ["-start_time"],
                "permissions": [
                    ("can_view_all_campaigns", "Can view all campaigns"),
                    ("can_disable_campaigns", "Can disable campaigns"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
