# Generated by Django 6.0.3 on 2026-04-05 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_campaign_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriber",
            options={
                "ordering": ["full_name"],
                "permissions": [
                    ("can_block_subscriber", "Can block subscriber"),
                    ("can_view_all_subscribers", "Can view all subscribers"),
                ],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылок",
            },
        ),
    ]
